### ISSUE TITLE
Swift 6.1 build time error: redefinition of module 'CNIO...'

### ISSUE THREAD

**Issue by MahdiBM** [apple/swift-nio#3204]
### Expected behavior

No errors.

### Actual behavior

Errors on project that builds fine with Swift 6.0 compiler:
```
/__w/my-app/my-app/.build/x86_64-unknown-linux-gnu/debug/CNIOWASI-tool.build/module.modulemap:1:8: error: redefinition of module 'CNIOWASI'
1 | module CNIOWASI {
  |        `- error: redefinition of module 'CNIOWASI'
2 |     umbrella header "/__w/my-app/my-app/.build/checkouts/swift-nio/Sources/CNIOWASI/include/CNIOWASI.h"
3 |     export *
```

I have noticed other module names as well. These are the ones I could quickly catch:
CNIOAtomics, CNIOLinux, CNIODarwin, CNIOWASI, CNIOBoringSSLShims

### Steps to reproduce

None. The project is private.

### If possible, minimal yet complete reproducer code (or URL to code)

None. The project is private. Haven't tried to minimally reproduce.

### SwiftNIO version/commit hash

2.81.0 tag.

### System & version information

`swift:6.1-noble` Docker image.

**Comment by Lukasa** [comment]
Thanks for filing this. Can you provide a complete build log? If necessary, feel free to provide it privately.

**Comment by MahdiBM** [comment]
where can I contact you privately? an email should be good enough, but anything else you have should also do it.

**Comment by Lukasa** [comment]
You can use the OSS Swift Slack DM, or you can email me. My work email address is on any of my git commits.

**Comment by MahdiBM** [comment]
Emailed with title 'Logs for https://github.com/apple/swift-nio/issues/3204'. Thanks for looking into this 🙂.

**Comment by Lukasa** [comment]
Hrm, this looks like a SwiftPM bug, where it's generating duplicate modulemaps for the `-tool` case and the product case. https://github.com/swiftlang/swift-package-manager/pull/8498 might be a fix? cc @dschaefer2

**Comment by dschaefer2** [comment]
Without a reproducing package, it's hard to say whether this fixed it but the error does look familiar.

**Comment by MahdiBM** [comment]
@dschaefer2 when can I expect that fix? Swift 6.1.1?

**Comment by dschaefer2** [comment]
Yup, see https://github.com/swiftlang/swift-package-manager/pull/8526

**Comment by dschaefer2** [comment]
Actually, it'll be in the next release off of release/6.1, which shouldn't be much later than 6.1.1 (which is Windows and Linux fixes only).

**Comment by MahdiBM** [comment]
I can confirm the project now compiles again on Swift 6.2 nightlies (the one bundled with Xcode 26 beta 2).
I had to fix some new macro-related errors but that's unrelated to this.

**Comment by MahdiBM** [comment]
Our project is doing well on Swift 6.2 so I think we can close this issue?
Although I hear some more folks are bumping into something similar to this even on 6.2.

**Comment by Lukasa** [comment]
Let's close this for now, we can always reopen.
