### ISSUE TITLE
Can't build SwiftNIOPosix in Release (using Pods as a packet manager)

### ISSUE THREAD

**Issue by madmag77** [apple/swift-nio#2073]
### Expected behavior
I expect I can build in release mode my app that uses SwiftNIO pod.
This is my pod (https://github.com/madmag77/STUNClient/blob/master/StunClient.podspec) that uses SwiftNIO as a dependency.

### Actual behavior
This is a sample app (https://github.com/madmag77/STUNClient/tree/master/iOSExampleWithPods) that can't be built in release mode when uses SwiftNIO pod version 2.38.

Output:
```
Ld /Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Intermediates.noindex/Pods.build/Release-iphoneos/SwiftNIOPosix.build/Objects-normal/arm64/Binary/NIOPosix normal arm64 (in target 'SwiftNIOPosix' from project 'Pods')
    cd /Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -L/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/SwiftNIOPosix -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/lib/swift -F/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/SwiftNIOPosix -F/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/CNIOAtomics -F/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/CNIODarwin -F/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/CNIOLinux -F/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/CNIOWindows -F/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/SwiftNIOConcurrencyHelpers -F/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/SwiftNIOCore -F/Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Products/Release-iphoneos/_NIODataStructures -filelist /Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Intermediates.noindex/Pods.build/Release-iphoneos/SwiftNIOPosix.build/Objects-normal/arm64/NIOPosix.LinkFileList -install_name @rpath/NIOPosix.framework/NIOPosix -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Intermediates.noindex/Pods.build/Release-iphoneos/SwiftNIOPosix.build/Objects-normal/arm64/NIOPosix_lto.o -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Intermediates.noindex/Pods.build/Release-iphoneos/SwiftNIOPosix.build/Objects-normal/arm64/NIOPosix.swiftmodule -framework CNIODarwin -framework CNIOLinux -framework CNIOWindows -framework NIOConcurrencyHelpers -framework NIOCore -framework _NIODataStructures -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Intermediates.noindex/Pods.build/Release-iphoneos/SwiftNIOPosix.build/Objects-normal/arm64/NIOPosix_dependency_info.dat -o /Users/artemgoncharov/Downloads/STUNClient/iOSExampleWithPods/DerivedData/STUNClient/Build/Intermediates.noindex/Pods.build/Release-iphoneos/SwiftNIOPosix.build/Objects-normal/arm64/Binary/NIOPosix

Undefined symbols for architecture arm64:
  "_catmc_nio_atomic__Bool_compare_and_exchange", referenced from:
      NIOPosix.PendingDatagramWritesManager.add(envelope: NIOCore.AddressedEnvelope<NIOCore.ByteBuffer>, promise: NIOCore.EventLoopPromise<()>?) -> Swift.Bool in PendingDatagramWritesManager.o
      NIOPosix.PendingStreamWritesManager.add(data: NIOCore.IOData, promise: NIOCore.EventLoopPromise<()>?) -> Swift.Bool in PendingWritesManager.o
  "_catmc_nio_atomic_long_add", referenced from:
      NIOPosix.MultiThreadedEventLoopGroup.next() -> NIOCore.EventLoop in MultiThreadedEventLoopGroup.o
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed> of NIOPosix.MultiThreadedEventLoopGroup.init(threadInitializers: [(NIOPosix.NIOThread) -> ()], selectorFactory: () throws -> NIOPosix.Selector<NIOPosix.NIORegistration>) -> NIOPosix.MultiThreadedEventLoopGroup in MultiThreadedEventLoopGroup.o
  "_catmc_nio_atomic_long_create_with_existing_storage", referenced from:
      variable initialization expression of NIOPosix.MultiThreadedEventLoopGroup.(index in _C2B1528F4FBA68A3DBFA89DBAEBE9D4D) : NIOConcurrencyHelpers.NIOAtomic<Swift.Int> in BaseSocket.o
      one-time initialization function for (nextEventLoopGroupID in _C2B1528F4FBA68A3DBFA89DBAEBE9D4D) in MultiThreadedEventLoopGroup.o
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed> of NIOPosix.MultiThreadedEventLoopGroup.init(threadInitializers: [(NIOPosix.NIOThread) -> ()], selectorFactory: () throws -> NIOPosix.Selector<NIOPosix.NIORegistration>) -> NIOPosix.MultiThreadedEventLoopGroup in MultiThreadedEventLoopGroup.o
  "_catmc_nio_atomic__Bool_store", referenced from:
      NIOPosix.BaseSocketChannel.close0(error: Swift.Error, mode: NIOCore.CloseMode, promise: NIOCore.EventLoopPromise<()>?) -> () in BaseSocketChannel.o
      NIOPosix.BaseSocketChannel.becomeActive0(promise: NIOCore.EventLoopPromise<()>?) -> () in BaseSocketChannel.o
      NIOPosix.PendingDatagramWritesManager.(didWrite in _DAB463F912477C8697B1F8AEBF8BD15A)(_: NIOPosix.IOResult<Swift.Int>, messages: Swift.UnsafeMutableBufferPointer<__C.CNIODarwin_mmsghdr>?) -> NIOPosix.OneWriteOperationResult in PendingDatagramWritesManager.o
      function signature specialization <Arg[0] = [Closure Propagated : closure #1 (NIOPosix.WriteMechanism) throws -> NIOPosix.OneWriteOperationResult in NIOPosix.PendingDatagramWritesManager.triggerAppropriateWriteOperations(scalarWriteOperation: (Swift.UnsafeRawBufferPointer, Swift.UnsafePointer<__C.sockaddr>, Swift.UInt32, Swift.Optional<NIOCore.AddressedEnvelope<NIOCore.ByteBuffer>.Metadata>) throws -> NIOPosix.IOResult<Swift.Int>, vectorWriteOperation: (Swift.UnsafeMutableBufferPointer<__C.CNIODarwin_mmsghdr>) throws -> NIOPosix.IOResult<Swift.Int>) throws -> NIOPosix.OverallWriteResult, Argument Types : [NIOPosix.PendingDatagramWritesManager@callee_guaranteed (@unowned Swift.UnsafeRawBufferPointer, @unowned Swift.UnsafePointer<__C.sockaddr>, @unowned Swift.UInt32, @guaranteed NIOCore.AddressedEnvelope<NIOCore.ByteBuffer>.Metadata?) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)@callee_guaranteed (@unowned Swift.UnsafeMutableBufferPointer<__C.CNIODarwin_mmsghdr>) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)]> of generic specialization <NIOPosix.PendingDatagramWritesManager> of (extension in NIOPosix):NIOPosix.PendingWritesManager.triggerWriteOperations(triggerOneWriteOperation: (NIOPosix.WriteMechanism) throws -> NIOPosix.OneWriteOperationResult) throws -> NIOPosix.OverallWriteResult in PendingWritesManager.o
      function signature specialization <Arg[0] = [Closure Propagated : closure #1 (NIOPosix.WriteMechanism) throws -> NIOPosix.OneWriteOperationResult in NIOPosix.PendingStreamWritesManager.triggerAppropriateWriteOperations(scalarBufferWriteOperation: (Swift.UnsafeRawBufferPointer) throws -> NIOPosix.IOResult<Swift.Int>, vectorBufferWriteOperation: (Swift.UnsafeBufferPointer<__C.iovec>) throws -> NIOPosix.IOResult<Swift.Int>, scalarFileWriteOperation: (Swift.Int32, Swift.Int, Swift.Int) throws -> NIOPosix.IOResult<Swift.Int>) throws -> NIOPosix.OverallWriteResult, Argument Types : [NIOPosix.PendingStreamWritesManager@callee_guaranteed (@unowned Swift.UnsafeRawBufferPointer) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)@callee_guaranteed (@unowned Swift.UnsafeBufferPointer<__C.iovec>) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)@callee_guaranteed (@unowned Swift.Int32, @unowned Swift.Int, @unowned Swift.Int) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)]> of generic specialization <NIOPosix.PendingStreamWritesManager> of (extension in NIOPosix):NIOPosix.PendingWritesManager.triggerWriteOperations(triggerOneWriteOperation: (NIOPosix.WriteMechanism) throws -> NIOPosix.OneWriteOperationResult) throws -> NIOPosix.OverallWriteResult in PendingWritesManager.o
      NIOPosix.PendingStreamWritesManager.(didWrite in _E8AD929129EAA2971226E80CBC6171E1)(itemCount: Swift.Int, result: NIOPosix.IOResult<Swift.Int>) -> NIOPosix.OneWriteOperationResult in PendingWritesManager.o
      generic specialization <NIOPosix.Socket> of NIOPosix.BaseSocketChannel.close0(error: Swift.Error, mode: NIOCore.CloseMode, promise: NIOCore.EventLoopPromise<()>?) -> () in SocketChannel.o
      ...
  "_catmc_nio_atomic__Bool_load", referenced from:
      NIOPosix.BaseSocketChannel.isActive.getter : Swift.Bool in BaseSocketChannel.o
      NIOPosix.BaseStreamSocketChannel.isWritable.getter : Swift.Bool in BaseStreamSocketChannel.o
      function signature specialization <Arg[0] = [Closure Propagated : closure #1 (NIOPosix.WriteMechanism) throws -> NIOPosix.OneWriteOperationResult in NIOPosix.PendingDatagramWritesManager.triggerAppropriateWriteOperations(scalarWriteOperation: (Swift.UnsafeRawBufferPointer, Swift.UnsafePointer<__C.sockaddr>, Swift.UInt32, Swift.Optional<NIOCore.AddressedEnvelope<NIOCore.ByteBuffer>.Metadata>) throws -> NIOPosix.IOResult<Swift.Int>, vectorWriteOperation: (Swift.UnsafeMutableBufferPointer<__C.CNIODarwin_mmsghdr>) throws -> NIOPosix.IOResult<Swift.Int>) throws -> NIOPosix.OverallWriteResult, Argument Types : [NIOPosix.PendingDatagramWritesManager@callee_guaranteed (@unowned Swift.UnsafeRawBufferPointer, @unowned Swift.UnsafePointer<__C.sockaddr>, @unowned Swift.UInt32, @guaranteed NIOCore.AddressedEnvelope<NIOCore.ByteBuffer>.Metadata?) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)@callee_guaranteed (@unowned Swift.UnsafeMutableBufferPointer<__C.CNIODarwin_mmsghdr>) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)]> of generic specialization <NIOPosix.PendingDatagramWritesManager> of (extension in NIOPosix):NIOPosix.PendingWritesManager.triggerWriteOperations(triggerOneWriteOperation: (NIOPosix.WriteMechanism) throws -> NIOPosix.OneWriteOperationResult) throws -> NIOPosix.OverallWriteResult in PendingWritesManager.o
      function signature specialization <Arg[0] = [Closure Propagated : closure #1 (NIOPosix.WriteMechanism) throws -> NIOPosix.OneWriteOperationResult in NIOPosix.PendingStreamWritesManager.triggerAppropriateWriteOperations(scalarBufferWriteOperation: (Swift.UnsafeRawBufferPointer) throws -> NIOPosix.IOResult<Swift.Int>, vectorBufferWriteOperation: (Swift.UnsafeBufferPointer<__C.iovec>) throws -> NIOPosix.IOResult<Swift.Int>, scalarFileWriteOperation: (Swift.Int32, Swift.Int, Swift.Int) throws -> NIOPosix.IOResult<Swift.Int>) throws -> NIOPosix.OverallWriteResult, Argument Types : [NIOPosix.PendingStreamWritesManager@callee_guaranteed (@unowned Swift.UnsafeRawBufferPointer) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)@callee_guaranteed (@unowned Swift.UnsafeBufferPointer<__C.iovec>) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)@callee_guaranteed (@unowned Swift.Int32, @unowned Swift.Int, @unowned Swift.Int) -> (@unowned NIOPosix.IOResult<Swift.Int>, @error @owned Swift.Error)]> of generic specialization <NIOPosix.PendingStreamWritesManager> of (extension in NIOPosix):NIOPosix.PendingWritesManager.triggerWriteOperations(triggerOneWriteOperation: (NIOPosix.WriteMechanism) throws -> NIOPosix.OneWriteOperationResult) throws -> NIOPosix.OverallWriteResult in PendingWritesManager.o
      NIOPosix.PendingStreamWritesManager.description.getter : Swift.String in PendingWritesManager.o
      NIOPosix.PipeChannel.description.getter : Swift.String in PipeChannel.o
      NIOPosix.DatagramChannel.isWritable.getter : Swift.Bool in SocketChannel.o
      ...
  "_catmc_nio_atomic__Bool_create_with_existing_storage", referenced from:
      NIOPosix.PendingDatagramWritesManager.init(msgs: Swift.UnsafeMutableBufferPointer<__C.CNIODarwin_mmsghdr>, iovecs: Swift.UnsafeMutableBufferPointer<__C.iovec>, addresses: Swift.UnsafeMutableBufferPointer<__C.sockaddr_storage>, storageRefs: Swift.UnsafeMutableBufferPointer<Swift.Unmanaged<Swift.AnyObject>>, controlMessageStorage: NIOPosix.UnsafeControlMessageStorage) -> NIOPosix.PendingDatagramWritesManager in PendingDatagramWritesManager.o
      NIOPosix.PendingStreamWritesManager.init(iovecs: Swift.UnsafeMutableBufferPointer<__C.iovec>, storageRefs: Swift.UnsafeMutableBufferPointer<Swift.Unmanaged<Swift.AnyObject>>) -> NIOPosix.PendingStreamWritesManager in PendingWritesManager.o
      function signature specialization <Arg[1] = Owned To Guaranteed, Arg[2] = Owned To Guaranteed> of generic specialization <NIOPosix.ServerSocket> of NIOPosix.BaseSocketChannel.init(socket: A, parent: NIOCore.Channel?, eventLoop: NIOPosix.SelectableEventLoop, recvAllocator: NIOCore.RecvByteBufferAllocator) throws -> NIOPosix.BaseSocketChannel<A> in SocketChannel.o
      function signature specialization <Arg[1] = Owned To Guaranteed, Arg[2] = Owned To Guaranteed> of generic specialization <NIOPosix.PipePair> of NIOPosix.BaseSocketChannel.init(socket: A, parent: NIOCore.Channel?, eventLoop: NIOPosix.SelectableEventLoop, recvAllocator: NIOCore.RecvByteBufferAllocator) throws -> NIOPosix.BaseSocketChannel<A> in SocketChannel.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Same errors I'm having when use command `pod lib lint` for the above pod:
```
-> StunClient (1.0.5)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | xcodebuild:  note: Planning
    - NOTE  | xcodebuild:  note: Building targets in dependency order
    - NOTE  | xcodebuild:  NIOPosix.BaseSocketChannel.close0(error: Swift.Error, mode: NIOCore.CloseMode, promise: NIOCore.EventLoopPromise<()>?) -> () in BaseSocketChannel.o
    - NOTE  | xcodebuild:  generic specialization <NIOPosix.Socket> of NIOPosix.BaseSocketChannel.close0(error: Swift.Error, mode: NIOCore.CloseMode, promise: NIOCore.EventLoopPromise<()>?) -> () in SocketChannel.o
    - NOTE  | xcodebuild:  merged generic specialization <NIOPosix.ServerSocket> of NIOPosix.BaseSocketChannel.close0(error: Swift.Error, mode: NIOCore.CloseMode, promise: NIOCore.EventLoopPromise<()>?) -> () in SocketChannel.o
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | xcodebuild:  note: Using codesigning identity override:
```

another evidence from the independent source - https://github.com/grpc/grpc-swift/issues/1369 - they are having the same issue.
 

### Steps to reproduce
1. git clone git@github.com:madmag77/STUNClient.git
2. cd STUNClient
3. pod lib lint

### If possible, minimal yet complete reproducer code (or URL to code)

no code needed to reproduce

### SwiftNIO version/commit hash

SwiftNIO 2.38

### System & version information

Please provide at the very least your operating system and Swift version
information.

Ideally, run

```
scripts/nio-diagnose -o nio-diagnose.md PID_OF_YOUR_NIO_PROGRAM
```

and attach (or paste) the resulting file `nio-diagnose.md` into this bug report
or send it to the SwiftNIO maintainers privately.

I've done the above and can send that file to the maintainers (need an email to send to).

**Comment by Lukasa** [comment]
This appear to be a transitive linkage issue: we're correctly linking the `NIOConcurrencyHelpers` framework, but not transitively linking the `CNIOAtomics` framework that it depends on. This causes these symbols to be missing. I'm surprised this linkage failure has happened: does it occur with older pod versions?

**Comment by rbrovko** [comment]
@Lukasa correct work with previous version StunClient (1.0.4) and dependency SwiftNIO (2.18.0) but only for Swift <=5.5 (Xcode <= 13.2.1)

**Comment by rbrovko** [comment]
I checked with SwiftNIO versions from https://github.com/CocoaPods/Specs/tree/master/Specs/e/8/6/SwiftNIO
Xcode 13.2.1 and SwiftNIO:
2.38.0 - failed
2.32.3 - failed
2.30.0 - failed
2.28.0 - failed
2.27.0 - failed
2.26.0 - failed
2.25.1 - success 

Xcode 13.3
2.25.1 - failed - Swift 5.6 didn't support
```
    - ERROR | xcodebuild:  SwiftNIO/Sources/NIO/CircularBuffer.swift:114:1: error: type 'CircularBuffer<Element>' does not conform to protocol 'MutableCollection'
    - ERROR | xcodebuild:  SwiftNIO/Sources/NIO/CircularBuffer.swift:114:1: error: unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'MutableCollection'
    - NOTE  | xcodebuild:  Swift.MutableCollection:8:12: note: 'subscript(_:)' declared here
    - NOTE  | xcodebuild:  Swift.MutableCollection:6:14: note: requirement 'subscript(_:)' declared here
    - ERROR | xcodebuild:  SwiftNIO/Sources/NIO/MarkedCircularBuffer.swift:132:1: error: type 'MarkedCircularBuffer<Element>' does not conform to protocol 'MutableCollection'
    - ERROR | xcodebuild:  SwiftNIO/Sources/NIO/MarkedCircularBuffer.swift:132:1: error: unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'MutableCollection'
```

**Comment by rbrovko** [comment]
I try `pod lib lint SwiftNIO.podspec` from tag `2.38.0` and get error too
```
 -> SwiftNIO (2.38.0)
    - NOTE  | url: The URL (https://apple.github.io/swift-nio/docs/current/NIO/index.html) is not reachable.
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | xcodebuild:  note: Planning
    - NOTE  | xcodebuild:  note: Building targets in dependency order
    - NOTE  | xcodebuild:  NIOPosix.BaseSocketChannel.close0(error: Swift.Error, mode: NIOCore.CloseMode, promise: NIOCore.EventLoopPromise<()>?) -> () in BaseSocketChannel.o
    - NOTE  | xcodebuild:  generic specialization <NIOPosix.ServerSocket> of NIOPosix.BaseSocketChannel.close0(error: Swift.Error, mode: NIOCore.CloseMode, promise: NIOCore.EventLoopPromise<()>?) -> () in SocketChannel.o
    - NOTE  | xcodebuild:  generic specialization <NIOPosix.Socket> of NIOPosix.BaseSocketChannel.close0(error: Swift.Error, mode: NIOCore.CloseMode, promise: NIOCore.EventLoopPromise<()>?) -> () in SocketChannel.o
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | xcodebuild:  note: Using codesigning identity override:
    - NOTE  | [watchOS] xcodebuild:  ld: warning: could not create compact unwind for _$ss16IndexingIteratorVy8NIOPosix27UnsafeControlMessageStorageVGAByxGStsWlTm: stack subl instruction is too different from dwarf stack size
    - NOTE  | [watchOS] xcodebuild:  ld: warning: could not create compact unwind for _$ss16IndexingIteratorVy8NIOPosix30UnsafeControlMessageCollectionVGAByxGStsWl: stack subl instruction is too different from dwarf stack size
    - NOTE  | [watchOS] xcodebuild:  ld: warning: could not create compact unwind for _$sSIy8NIOPosix30UnsafeControlMessageCollectionVGSIyxGSlsWl: stack subl instruction is too different from dwarf stack size
    - NOTE  | [watchOS] xcodebuild:  ld: warning: could not create compact unwind for _$ss5SliceVy8NIOPosix30UnsafeControlMessageCollectionVGAByxGSlsWl: stack subl instruction is too different from dwarf stack size

```

**Comment by rbrovko** [comment]
@Lukasa need add `s.dependency 'CNIOAtomics', s.version.to_s` to `SwiftNIOPosix.podspec` and
- pod lib lint SwiftNIOPosix.podspec - success 
- pod lib lint SwiftNIO.podspec - success

**Comment by rbrovko** [comment]
I use personal specs repo https://github.com/rbrovko/specs and changed podspecs from 2.38.0 - 2.38.1-r
`Podfile.lock`
```
  - StunClient (1.0.5-r):
    - SwiftNIO (= 2.38.1-r)
  - SwiftNIO (2.38.1-r):
    - SwiftNIOCore (= 2.38.1-r)
    - SwiftNIOEmbedded (= 2.38.1-r)
    - SwiftNIOPosix (= 2.38.1-r)
  - SwiftNIOConcurrencyHelpers (2.38.1-r):
    - CNIOAtomics (= 2.38.1-r)
  - SwiftNIOCore (2.38.1-r):
    - CNIOLinux (= 2.38.1-r)
    - SwiftNIOConcurrencyHelpers (= 2.38.1-r)
  - SwiftNIOEmbedded (2.38.1-r):
    - _NIODataStructures (= 2.38.1-r)
    - SwiftNIOCore (= 2.38.1-r)
  - SwiftNIOPosix (2.38.1-r):
    - _NIODataStructures (= 2.38.1-r)
    - CNIOAtomics (= 2.38.1-r)
    - CNIODarwin (= 2.38.1-r)
    - CNIOLinux (= 2.38.1-r)
    - CNIOWindows (= 2.38.1-r)
    - SwiftNIOConcurrencyHelpers (= 2.38.1-r)
    - SwiftNIOCore (= 2.38.1-r)
```

**Comment by Lukasa** [comment]
Seems to be the same issue as grpc/grpc-swift#1369.

@glbrntt any idea whether we changed the pod spec generation here? If not, I think the SwiftPM we're using is generating a different dependency graph.

**Comment by glbrntt** [comment]
Nothing has changed recently in the pod spec generation.

A few things I found:
- From https://github.com/apple/swift-nio/issues/2073#issuecomment-1100065015 it looks like `2.26.0` was the release where this broke
- In [2.26.0](https://github.com/apple/swift-nio/releases/tag/2.26.0) the dependency on `NIOAtomics` was removed from the `NIO` target (https://github.com/apple/swift-nio/pull/1719) which has subsequently become `NIOCore`, `NIOPosix` and `NIOEmbedded`.
- `NIOPosix` uses atomics directly but never imports `NIOAtomics` (only indirectly via `NIOConcurrencyHelpers`), nor is this dependency expressed in `Package.swift`

I suspect this is the problem: `NIOPosix` should declare an explicit dependency on `NIOAtomics`..

**Comment by Lukasa** [comment]
I think dropping `CNIOAtomics` was right for SwiftPM but wrong for Cocoapods. It's a good observation that we removed the explicit dependency in 2.26.0, and when we combine it with [this info](https://github.com/grpc/grpc-swift/issues/1369#issuecomment-1099888830) I think my theory is that Cocoapods is not behaving sensibly with `@inlinable` exposing symbols from a transitive dependency.

This suggests we might need to update the Cocoapods generation tool to express a dependency on _all transitive dependencies_ just in case we expose a symbol via an `@inlinable`.

**Comment by glbrntt** [comment]
> I think dropping `CNIOAtomics` was right for SwiftPM but wrong for Cocoapods. 

Agreed. 

> This suggests we might need to update the Cocoapods generation tool to express a dependency on _all transitive dependencies_ just in case we expose a symbol via an `@inlinable`.

That may well work and is reasonably straightforward to do in this instance (the libraries from this repo). 

However, if it really does require _all_ transitive dependencies then it quickly becomes unwieldy when package dependencies are introduced (e.g. consider NIO HTTP/2).

**Comment by Lukasa** [comment]
Can we not drive SwiftPM to produce this using something like `dump-package` or `describe`?

**Comment by Lukasa** [comment]
I _think_ `dump-package` gives us enough info to programmatically walk the dependency tree to find the full graph.

**Comment by glbrntt** [comment]
Neither tool gives us the dependencies of product dependencies.

**Comment by Lukasa** [comment]
Indeed it does not, but `dump-package` tells us which package dependency the product dependency comes from _and_ the URL to that package, so we can recursively clone our way to success. I can throw a prototype together real quick.

**Comment by glbrntt** [comment]
@madmag77 this should be resolved in the latest NIO releases (2.40.0), please let us know if it isn't!

**Comment by the-real-adammork** [comment]
We're still seeing this issue w/ `2.40.0` and Xcode 14.1

```
    Ld /Users/adam/Library/Developer/Xcode/DerivedData/App-cegpukiwafoqhibkzmfgccxqvzkw/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/SwiftNIOHTTP2.build/Objects-normal/x86_64/Binary/NIOHTTP2 normal x86_64 (in target 'SwiftNIOHTTP2' from project 'Pods')
      
....

    Undefined symbols for architecture x86_64:
      "_catmc_nio_atomic__Bool_create_with_existing_storage", referenced from:
          _$s8NIOHTTP218HTTP2StreamChannelC9allocator6parent11multiplexer8streamID16targetWindowSize26outboundBytesHighWatermark0mn3LowP00H8DataTypeAC7NIOCore19ByteBufferAllocatorV_AL0D0_pAA0bC11MultiplexerCAA0bcI0VSgs5Int32VS2iAA0bcrS0Otcfc in HTTP2StreamChannel.o
      "_catmc_nio_atomic__Bool_load", referenced from:
          _$s8NIOHTTP218HTTP2StreamChannelC25networkActivationReceivedyyF in HTTP2StreamChannel.o
          _$s8NIOHTTP218HTTP2StreamChannelC10isWritableSbvg in HTTP2StreamChannel.o
          _$s8NIOHTTP218HTTP2StreamChannelC8isActiveSbvg in HTTP2StreamChannel.o
      "_catmc_nio_atomic__Bool_store", referenced from:
          _$s8NIOHTTP218HTTP2StreamChannelC17performActivationyyF in HTTP2StreamChannel.o
          _$s8NIOHTTP218HTTP2StreamChannelC16errorEncountered33_5469B6D9C081B4CA091A1908ADC063BCLL0E0ys5Error_p_tF in HTTP2StreamChannel.o
          _$s8NIOHTTP218HTTP2StreamChannelC14modifyingState33_5469B6D9C081B4CA091A1908ADC063BCLLyxxAA0cdF0AELLOzKXEKlFyt_Tg5013$s8NIOHTTP218bcd25C15closedWhileOpen33_5469ghijklm14BCLLyyFyAA0cD5F11AELLOzXEfU_Tf1ncn_n in HTTP2StreamChannel.o
          _$s8NIOHTTP218HTTP2StreamChannelC25networkActivationReceivedyyF in HTTP2StreamChannel.o
          _$s8NIOHTTP218HTTP2StreamChannelC6write0_7promisey7NIOCore6NIOAnyV_AF16EventLoopPromiseVyytGSgtF in HTTP2StreamChannel.o
          _$s8NIOHTTP218HTTP2StreamChannelC6write0_7promisey7NIOCore6NIOAnyV_AF16EventLoopPromiseVyytGSgtFys6ResultOyyts5Error_pGcfU_ in HTTP2StreamChannel.o
          _$s8NIOHTTP218HTTP2StreamChannelC13closedCleanly33_5469B6D9C081B4CA091A1908ADC063BCLLyyF in HTTP2StreamChannel.o
```

**Comment by Lukasa** [comment]
We’ve largely abandoned cocoapods, but this appears most likely to be an issue with cocoapods itself. I recommend asking the cocoapods team for help.

**Comment by the-real-adammork** [comment]
> We’ve largely abandoned cocoapods, but this appears most likely to be an issue with cocoapods itself. I recommend asking the cocoapods team for help.

ok thanks
