### ISSUE TITLE
Swift-nio failing to build with Swift version 4.2

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift-nio#2241]
### Expected behavior
Expected the project to build successfully with Swift version 4.2

### Actual behavior
When building with 4.2, the compilation fails with 
```
swift-nio/Sources/NIOPosix/ServerSocket.swift:132:64: error: value of optional type 'String?' must be unwrapped to a value of type 'String'
```

### Steps to reproduce
1. Git clone https://github.com/apple/swift-nio
2. Git checkout f5448fbbc24495a6659ef64df4dd3c1fc4a0fb11
3. swift build  --verbose --configuration release -Xswiftc -swift-version -Xswiftc 4.2

Note that the build succeeds when you use version `5.` instead

### SwiftNIO version/commit hash
[`f5448fbbc24495a6659ef64df4dd3c1fc4a0fb11`](f5448fbbc24495a6659ef64df4dd3c1fc4a0fb11)

**Comment by justice-adams-apple** [comment]
This popped up when investigating https://github.com/apple/swift-source-compat-suite/pull/695

**Comment by dnadoba** [comment]
NIO 2.x.x only supports Swift 5.4 and newer. I think the right move will be to remove Swift 4.x support from the compatibility suite, at least for NIO 2.x

**Comment by justice-adams-apple** [comment]
@dnadoba Sure, I can do that. Thank you. Feel free to close this issue!
