### PR TITLE
fix: conditionally define RENAME_* macros

### PR DESCRIPTION
**Pull request by Austinpayne**
When using `-Xcc -Werror` flags redefining macros results in a compilation error.

### Motivation:

Fixes regression in https://github.com/apple/swift-nio/pull/2628.

### Modifications:

Check if `RENAME_*` macros are already defined before before defining for the musl case.

### Result:

NIO now compiles when using `-Werror`.

### CODE REVIEW

**Review by glbrntt — APPROVED** [review]
Thank you!
