### ISSUE TITLE
Flaky test: NIOAsyncWriterTests.testWriterDeinitialized_whenWriterFinished

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#2427]
Failed in #2425 on Swift 5.6: https://ci.swiftserver.group/job/swift-nio2-swift56-prb/1026/consoleFull.

```
10:11:24 Test Case 'NIOAsyncWriterTests.testWriterDeinitialized_whenWriterFinished' started at 2023-05-16 09:11:24.341
10:11:24 /code/Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift:157: error: NIOAsyncWriterTests.testWriterDeinitialized_whenWriterFinished : XCTAssertEqual failed: ("1") is not equal to ("0") - 
10:11:24 Test Case 'NIOAsyncWriterTests.testWriterDeinitialized_whenWriterFinished' failed (0.002 seconds)
```
