### PR TITLE
Fixed compile errors on windows

### PR DESCRIPTION
**Pull request by toluRV**
Fixed compile error that seems to be caused by https://github.com/apple/swift-nio/pull/2266/

### Motivation:

Fixed compilation errors on Windows.

### Modifications:

Fixed typos

### Result:

Devs should be able to compile on Windows

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
Thanks!

**Comment by Lukasa** [comment]
@swift-server-bot test this please
