### ISSUE TITLE
flaky test ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1147]
```
20:40:38 Test Case 'ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError' started at 2019-09-24 19:40:38.146
20:40:38 /code/Tests/NIOTests/ChannelTests.swift:2242: error: ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError : failed - just worked
20:40:38 Test Case 'ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError' failed (0.038 seconds)
```

happened in CI: https://ci.swiftnio.io/job/swift-nio2/316/consoleFull

**Comment by weissi** [comment]
failed again in CI 5.1:

```
17:11:41 Test Case 'ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError' started at 2020-01-26 17:11:41.204
17:11:41 /code/Tests/NIOTests/ChannelTests.swift:2256: error: ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError : failed - just worked
17:11:41 Test Case 'ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError' failed (0.103 seconds)
```

**Comment by glbrntt** [comment]
and again in CI 5.0:

```
11:53:19 Test Case 'ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError' started at 2020-06-24 10:53:19.978
11:53:19 /code/Tests/NIOTests/ChannelTests.swift:2237: error: ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError : XCTAssertThrowsError failed: did not throw error - 
11:53:20 Test Case 'ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError' failed (0.035 seconds)
```

**Comment by weissi** [comment]
heh, seems to be about once every 4 months :P

**Comment by Lukasa** [comment]
CI on 5.3:

```
07:12:02 Test Case 'ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError' started at 2021-01-13 07:12:02.427
07:12:02 /code/Tests/NIOTests/ChannelTests.swift:2237: error: ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError : XCTAssertThrowsError failed: did not throw error - 
07:12:02 Test Case 'ChannelTests.testConnectWithECONNREFUSEDGetsTheRightError' failed (0.116 seconds)
```

**Comment by glbrntt** [comment]
Failed again in https://github.com/apple/swift-nio/pull/1922 on Swift 5.2

**Comment by glbrntt** [comment]
Failed again in https://github.com/apple/swift-nio/pull/2690 on 5.10
