### ISSUE TITLE
The tests stopped building for linux and Android with the latest Swift System 1.7.0 tag

### ISSUE THREAD

**Issue by finagolfin** [apple/swift-nio#3622]
### Expected behavior
The tests to build fine.

### Actual behavior
My Android CI [failed when cross-compiling the tests today](https://github.com/finagolfin/swift-android-sdk/actions/runs/27405452951/job/80993376037), despite the exact same NIO commit 7586225bc working fine yesterday, [when the latest System tag was 1.6.5](https://github.com/finagolfin/swift-android-sdk/actions/runs/27336244928/job/80802829526#step:19:35).

### Steps to reproduce
I can reproduce on linux with the following

1. > ~/swift-6.3.2-RELEASE-ubi9/usr/bin/swift package update
Fetching https://github.com/apple/swift-system.git from cache
Fetched https://github.com/apple/swift-system.git from cache (0.52s)
Fetching https://github.com/apple/swift-collections.git from cache
Fetched https://github.com/apple/swift-collections.git from cache (0.53s)
Fetching https://github.com/apple/swift-atomics.git from cache
Fetched https://github.com/apple/swift-atomics.git from cache (0.46s)
Computing version for https://github.com/apple/swift-atomics.git
Computed https://github.com/apple/swift-atomics.git at 1.3.0 (1.69s)
Computing version for https://github.com/apple/swift-system.git
Computed https://github.com/apple/swift-system.git at 1.7.0 (0.21s)
Computing version for https://github.com/apple/swift-collections.git
Computed https://github.com/apple/swift-collections.git at 1.6.0 (0.28s)
Creating working copy for https://github.com/apple/swift-collections.git
Working copy of https://github.com/apple/swift-collections.git resolved at 1.6.0
Creating working copy for https://github.com/apple/swift-system.git
Working copy of https://github.com/apple/swift-system.git resolved at 1.7.0
Creating working copy for https://github.com/apple/swift-atomics.git
Working copy of https://github.com/apple/swift-atomics.git resolved at 1.3.0
2. > ~/swift-6.3.2-RELEASE-ubi9/usr/bin/swift build --build-tests

### SwiftNIO version/commit hash

Irrelevant but 7586225bc

### System & version information

I reproduced with recent 6.4 and 6.5 snapshot toolchains also, running on Fedora 40 x86_64.

**Comment by glbrntt** [comment]
Thanks for filing this, this is a `swift-system` issue – the maintainers have been notified.

**Comment by MahdiBM** [comment]
Not sure if we're having the same issue, but I'm also seeing this on 6.3-noble debug builds in [swift-dns unit/integration tests](https://github.com/swift-dns/swift-dns/actions):

```bash
/__w/swift-dns/swift-dns/.build/checkouts/swift-nio/Sources/_NIOFileSystem/FileInfo.swift:206:29: error: property 'st_mode' is not available due to missing import of defining module 'CSystem' [#MemberImportVisibility]
 20 | @preconcurrency import Glibc
 21 | import CNIOLinux
 22 | #elseif canImport(Musl)
    | `- note: add import of module 'CSystem'
 23 | @preconcurrency import Musl
 24 | import CNIOLinux
    :
204 |         // common between Darwin and Glibc.
205 |         hasher.combine(stat.st_dev)
206 |         hasher.combine(stat.st_mode)
    |                             `- error: property 'st_mode' is not available due to missing import of defining module 'CSystem' [#MemberImportVisibility]
207 |         hasher.combine(stat.st_nlink)
208 |         hasher.combine(stat.st_ino)
```

If these are not the same, I can create a dedicated issue.

**Comment by finagolfin** [comment]
Yep, same errors with my linux commands above, @MahdiBM. 👍

**Comment by glbrntt** [comment]
cc @glessard

**Comment by glessard** [comment]
@jrflat is working on a fix for the 1.7.x branch.

**Comment by glessard** [comment]
Fixed in https://github.com/apple/swift-system/releases/tag/1.7.2

**Comment by finagolfin** [comment]
The Android build failed with different errors, which [this tag did nothing to fix](https://github.com/finagolfin/swift-android-sdk/actions/runs/27447499818/job/81135663384#step:19:35).

**Comment by finagolfin** [comment]
I just checked the new 1.7.2 tag on linux with the build commands above, and it is still failing there too, with the same errors as Android:
```
/home/finagolfin/swift-nio/Tests/NIOFSIntegrationTests/FileSystemTests.swift:1302:42: error: 'FileType' is ambiguous for type lookup in this context
1300 |     }
1301 |
1302 |     func testReplaceFile(_ existingType: FileType?, with replacementType: FileType) async throws {
     |                                          `- error: 'FileType' is ambiguous for type lookup in this context
1303 |         func makeRegularFile(at path: NIOFilePath) async throws {
1304 |             try await self.fs.withFileHandle(

/home/finagolfin/swift-nio/Sources/NIOFS/FileType.swift:28:15: note: found this candidate
 26 |
 27 | /// The type of a file system object.
 28 | public struct FileType: Hashable, Sendable {
    |               `- note: found this candidate
 29 |     internal enum Wrapped: Hashable, Sendable, CaseIterable {
 30 |         case regular

/home/finagolfin/swift-nio/.build/checkouts/swift-system/Sources/System/FileSystem/FileType.swift:38:15: note: found this candidate
 36 | @frozen
 37 | @available(System 99, *)
 38 | public struct FileType: RawRepresentable, Sendable, Hashable, Codable {
    |               `- note: found this candidate
 39 |
 40 |   /// The raw file-type bits from the C mode.

/home/finagolfin/swift-nio/Tests/NIOFSIntegrationTests/FileSystemTests.swift:1302:75: error: 'FileType' is ambiguous for type lookup in this context
1300 |     }
1301 |
1302 |     func testReplaceFile(_ existingType: FileType?, with replacementType: FileType) async throws {
     |                                                                           `- error: 'FileType' is ambiguous for type lookup in this context
1303 |         func makeRegularFile(at path: NIOFilePath) async throws {
1304 |             try await self.fs.withFileHandle(

/home/finagolfin/swift-nio/Sources/NIOFS/FileType.swift:28:15: note: found this candidate
 26 |
 27 | /// The type of a file system object.
 28 | public struct FileType: Hashable, Sendable {
    |               `- note: found this candidate
 29 |     internal enum Wrapped: Hashable, Sendable, CaseIterable {
 30 |         case regular

/home/finagolfin/swift-nio/.build/checkouts/swift-system/Sources/System/FileSystem/FileType.swift:38:15: note: found this candidate
 36 | @frozen
 37 | @available(System 99, *)
 38 | public struct FileType: RawRepresentable, Sendable, Hashable, Codable {
    |               `- note: found this candidate
 39 |
 40 |   /// The raw file-type bits from the C mode.
```
The Stat errors Mahdi listed are now gone.

**Comment by glessard** [comment]
@finagolfin does removing `import SystemPackage` from line 18 of "NIOFSIntegrationTests/FileSystemTests.swift" resolve the ambiguity on Linux?
It does on macOS but I don't have a usable linux handy.

**Comment by finagolfin** [comment]
[Easy to set up a linux container on macOS](https://forums.swift.org/t/building-a-linux-aarch64-toolchain-on-macos-with-containerization/84347) too, 😉 I'll check that import change.

**Comment by curmudg-eon** [comment]
I was able to confirm that the issue is also fixed in linux by dropping `import SystemPackage` locally. I will put up a PR for this.

**Comment by finagolfin** [comment]
Yep, that change fixed linux, including seemingly not breaking with System 1.4.0 checked out also, and [Android CI finally passes](https://github.com/finagolfin/swift-android-sdk/actions/runs/27452126057).
